### ISSUE TITLE
Aggiungere Account MEGA

### ISSUE THREAD

**Issue by vegruz** [404notfoundunipd/premi-documents#19]
Aggiungere Account MEGA alla sezione metodi di condivisione nel documento Norme di progetto.

**Comment by enricodlz** [comment]
MEGA
Inoltre, sarà disponibile un'account Mega, che conterrà le esportazioni delle VM con Ubuntu Desktop. E' stato scelto questo servizio cloud in quanto non c'è la necessità di un software di versionamento, inoltre dà a disposizione 50GB di spazio gratuito, per noi necessario per poter memorizzare file di grosse di dimensioni come le VM.
