### ISSUE TITLE
Aggiunta Termini al glossario

### ISSUE THREAD

**Issue by evilmastermind** [404notfoundunipd/premi-documents#22]
Questi sono i tre che mi mancavano... per parlare di mega pero' si sono aggiunti anche 'Virtual Machine' 'Ubuntu Desktop' e 'servizio cloud' D: avete gia' fatto le definizioni per questi?

ticket corrisponde ad un compito da portare a termine all'interno di un progetto, 
che puo' essere la correzione di un errore, l'aggiunta di una funzionalita', la verifica di
una parte del codice o molte altre cose.

commit e' l'azione di salvataggio delle modifiche apportate ad un branch all'interno di una repository.

merge , all'interno di una repository, significa riunire un branch di copia con il branch originale, 
aggiornando solamente quei files che sono stati modificati nel branch di copia indipendentemente
dai cambiamenti che sono avvenuti nel branch originale durante il periodo di separazione dei due.

**Comment by vegruz** [comment]
No i primi tre non sono ancora stati aggiunti... :)

**Comment by vegruz** [comment]
Li aggiungo io con relative definizioni...

**Comment by evilmastermind** [comment]
Ok grazie mille
